project: devops-sandbox
environment: sandbox
onepassworditems:
  - name: docker-registry-credentials
    itemPath: "vaults/EnvironmentKeys/items/docker-registry-credentials"
    secretType: kubernetes.io/dockerconfigjson
main:
  name: app
  enabled: true
  type: apache
  image: '471112881638.dkr.ecr.us-east-1.amazonaws.com/devops-sandbox/frontend:qa-frontend-1935e9a7-1738613936'
  resources: {}
  port: 80
  replicaCount: 3
  loadBalancer:
    enabled: true
    name: k8s-devops-sandbox
    type: preexisting
    targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:471112881638:targetgroup/sandbox-alb-tg/e94c9f61e2eb1d7c
    securityGroupID: sg-0f5b703fcc7e2d268 # allow-http-from-all
worker:
  name: worker
  enabled: true
  type: php
  image: '471112881638.dkr.ecr.us-east-1.amazonaws.com/devops-sandbox/worker:qa-worker-1935e9a7-1738613936'
  command: ["/app/bin/loop.php"]
  args: 
    - --env=qa
  pullPolicy: Always
  resources: {}
  replicaCount: 3
