project:
environment:
onepassworditems:
  - name:
    itemPath:
    secretType:
main:
  name:
  enabled:
  type:
  image:
  resources: {}
  port:
  replicaCount:
  loadBalancer:
    name:
    targetGroupARN:
    securityGroupID:
  pdb:
    # (Optional) Minimum number of frontend pods that must be available during disruptions
    minAvailable: 1
worker:
  name:
  enabled:
  type:
  image:
  command:
  args:
    -
  pullPolicy:
  resources:
  replicaCount:
  pdb:
    # (Optional) Minimum number of worker pods that must be available during disruptions
    minAvailable: 1
