project: 
environment: 
onepassworditems:
- name: 
  itemPath: 
  secretType: 
- name: 
  itemPath: 
main:
  name: 
  enabled: 
  type: 
  image: 
  resources:
    requests:
      cpu:  # in millicores
      memory:  # in mebibytes
    limits:
      cpu:  # in millicores
      memory:  # in mebibytes
  port: 
  envFrom:
  - secretRef:
      name: 
  loadBalancer:
    name: 
    targetGroupARN: 
    securityGroupID: 
  autoscaling:
    enabled: 
    minReplicaCount: 
    maxReplicaCount: 
    cpuUtilizationPercentage: 
    memoryUtilizationPercentage: 
  # Revision history limit for the deployment. This is the number of old ReplicaSets to retain
  # Set to 0 to disable revision history. If not set, defaults to 3
  revisionHistoryLimit : 3
worker:
  name: 
  enabled: 
  type: 
  image: 
  command: 
  pullPolicy: 
  resources:
    requests:
      cpu:  # in millicores
      memory:  # in mebibytes
    limits:
      cpu:  # in millicores
      memory:  # in mebibytes
  autoscaling:
    enabled: 
    minReplicaCount: 
    maxReplicaCount: 
    cpuUtilizationPercentage: 
    memoryUtilizationPercentage: 
  # Revision history limit for the deployment. This is the number of old ReplicaSets to retain
  # Set to 0 to disable revision history. If not set, defaults to 3
  revisionHistoryLimit : 3