{{- if .Values.config -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-helm3.fullname" . }}-config
  namespace: {{ .Values.namespace }}    
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}:
    {{- toYaml $value | nindent 4 }}
    {{- end }}
{{- end }}