apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-helm3.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}  
  labels:
    {{- include "generic-helm3.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "generic-helm3.selectorLabels" . | nindent 4 }}
