path: some/path
frontend:
  - name: frontend
    enabled: true
    image: "php:8.1.22-apache-bullseye"
    pullPolicy: IfNotPresent
    resources: {}
    port: 80
    replicaCount: 2
    host: php-app.local
    tls:
      secretRef: php-app-tls # pragma: allowlist secret

worker:
  - name: worker
    enabled: true
    image: "php:8.1.22-apache-bullseye"
    pullPolicy: IfNotPresent
    resources: {}
    replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
# keyinjection:
#   - name: hub-api-key
#     secretName: hub-api-key # pragma: allowlist secret
#     mountPath: /app/.hub-api-key
#   - name: test-api-key
#     secretName: test-api-key # pragma: allowlist secret
#     mountPath: /app/.test-api-key
