# -- To nest folders in flux use underscores which will map to sub-directories
project: breeze
environment: qa
version: 1.0.0

frontend:
  - name: frontend
    enabled: true
    type: php
    image: "php:8.1.22-apache-bullseye"
    pullPolicy: IfNotPresent
    secretsRef: qa-environemnt-variables # pragma: allowlist secret
    resources: {}
    port: 80
    replicaCount: 2
    host: php-app.local
    tls:
      secretRef: php-app-tls # pragma: allowlist secret
    imagepolicy:
      pattern: ^DEVOPS-338-deploy-breeze-qa-api-[a-fA-F0-9]+-(?P<ts>.*)

worker:
  - name: worker
    enabled: true
    type: php
    image: "php:8.1.22-apache-bullseye"
    pullPolicy: IfNotPresent
    secretsRef: qa-environemnt-variables # pragma: allowlist secret
    resources: {}
    replicaCount: 1
    imagepolicy:
      pattern: ^DEVOPS-338-deploy-breeze-qa-api-[a-fA-F0-9]+-(?P<ts>.*)

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
# keyinjection:
#   - name: hub-api-key
#     secretName: hub-api-key # pragma: allowlist secret
#     mountPath: /app/.hub-api-key
#   - name: test-api-key
#     secretName: test-api-key # pragma: allowlist secret
#     mountPath: /app/.test-api-key
