{{- if .Values.migrations }}
{{- if eq .Values.migrations.enabled true }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.migrations.name }}
  generateName: {{ $.Release.Namespace }}-migrations-job-
  namespace: {{ $.Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 4
  template:
    spec:
      restartPolicy: {{ $.Values.migrations.restartPolicy }}
      containers:
      - name: {{ $.Values.migrations.name }}-job
        command: {{ $.Values.migrations.command }}
        image: "{{ $.Values.migrations.image }}"
        args:
          {{- range $.Values.migrations.args }}
            - {{ . }}
          {{- end }}
        envFrom: {{- toYaml $.Values.migrations.envFrom | nindent 12 }}
{{- end -}}
{{- end -}}
