{{- if and .Values.worker.enabled .Values.worker.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.worker.name }}-worker-pdb
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ .Values.worker.name | quote }}
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.worker.name | quote }}
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
{{- end }}
