{{- range $key, $value := .Values.onepassworditems }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: {{ $value.secretType | default "opaque"}}
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  itemPath: {{ $value.itemPath | quote }}
{{- end -}}
