{{- if or (not .Values.tool) (eq .Values.tool "") (eq .Values.tool "flux") }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: {{ .Release.Name | quote }}
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: tithelybot@users.noreply.github.com
        name: tithelybot
      messageTemplate: |-
        "Updated by Flux - {{ .Release.Name }}"
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    {{- template "path" . }}
    strategy: Setters
{{- end }}
