{{- range $key, $value := .Values.worker }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: {{ $.Release.Namespace }}-{{ $value.name }}
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: {{ $value.imagepolicy.pattern }}
  imageRepositoryRef:
    name: {{ $.Values.project | replace "_" "-"  }}
  policy:
    numerical:
      order: asc
{{- end -}}
{{- range $key, $value := .Values.frontend }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: {{ $.Release.Namespace }}-{{ $value.name }}
  namespace: flux-system
spec:
  {{- if (or (empty $value.imagepolicy.repositoryType) (eq $value.imagepolicy.repositoryType "ecr")) }}
  filterTags:
    extract: $ts
    pattern: {{ $value.imagepolicy.pattern }}
  {{- end }}
  imageRepositoryRef:
    {{- if and $value.imagepolicy.repositoryType (eq $value.imagepolicy.repositoryType "docker") }}
    name: {{ $.Values.project | replace "_" "-" }}-docker
    {{- else }}
    name: {{ $.Values.project | replace "_" "-" }}
    {{- end }}
  {{- if and $value.imagepolicy.repositoryType (eq $value.imagepolicy.repositoryType "docker") }}
  policy:
    semver:
      range: {{ $value.imagepolicy.semverRange }}
  {{- else }}
  policy:
    numerical:
      order: asc
  {{- end }}
  {{- end }}
