{{- range $key, $value := .Values.frontend }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $value.name | quote }}
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $value.host }}`)
      kind: Rule
      services:
        - name: {{ $value.name | quote }}
          namespace: {{ $.Release.NameSpace | quote }}
          port: {{ $value.port }}
  tls:
    # domains:
    #   - main: {{ $value.host | quote }}
    secretName:  {{ $value.tls.secretRef | quote }}
{{- end -}}
