{{- range $key, $value := .Values.frontend }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ $value.host | quote }}
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: {{ $value.port }}
  tls:
    domains:
      - main: {{ $value.host | quote }}
    secretName:  {{ $value.tls.secretRef | quote }}
{{- end -}}
