{{- range $key, $value := .Values.frontend }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Namespace }}-{{ $value.name }}
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    {{- if $value.clientIP }} # Match to clientIP instead of host
    - match: ClientIP(`{{ $value.clientIP }}`)
    {{- else if contains "*." $value.host }}
    - match: HostRegexp(`{subdomain:[a-z0-9]+}.{{ $value.host | replace "*." "" }}`)
    {{- else }}
    - match: Host(`{{ $value.host }}`)
    {{- end }}
      kind: Rule
      {{- if contains "*." $value.host }}
      priority: 1
      {{- else if contains "api" $value.host }}
      priority: 2
      {{- end }}
      services:
        - name: {{ $value.name | quote }}
          kind: TraefikService
          namespace: {{ $.Release.Namespace | quote }}
          port: {{ $value.port }}
  tls:
    # domains:
    #   - main: {{ $value.host | quote }}
    secretName:  {{ $value.tls.secretRef | quote }}
{{- end -}}
