{{- range $key, $value := .Values.frontend }}
{{- if and $value.loadBalancer $value.loadBalancer.enabled (eq $value.loadBalancer.type "application") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ $value.name }}
    app.kubernetes.io/component: Ingress
    app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]' # Specify the ports to listen on
    alb.ingress.kubernetes.io/ssl-redirect: "443" # Redirect HTTP to HTTPS
    # alb.ingress.kubernetes.io/wafv2-acl-arn: # TBD
spec:
  ingressClassName: alb
  tls: # Certificate discovery
  - hosts:
    - {{ $value.loadBalancer.tls.hosts }}
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $value.name }} # This is the name of the kubernetes service that will become a target group
              port:
                number: 80
  selector:
    app.kubernetes.io/name: {{ $value.name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ $value.name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
spec:
  ports:
  - name: http
    targetPort: {{ $value.port }}
    port: {{ $value.port }}
  selector:
    app.kubernetes.io/name: {{ $value.name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
{{- end }}
{{- end }}
