---
{{- range $key, $value := .Values.frontend }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "serviceLabels" . | indent 4 }}
spec:
  ports:
  - name: http
    targetPort: {{ $value.port }}
    port: {{ $value.port }}
  selector:
  {{- include "frontendLabels" . | indent 4 }}
{{- end }}
