{{- range $key, $value := .Values.frontend }}
{{- if and $value.loadBalancer $value.loadBalancer.enabled (eq $value.loadBalancer.type "network") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ $value.name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ $value.loadBalancer.sslCertArn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https # References below name
spec:
  ports:
  - name: http
    targetPort: {{ $value.port }}
    port: 80
    protocol: TCP
  - name: https
    targetPort: {{ $value.port }}
    port: 443
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ $value.name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
  type: LoadBalancer
{{- end }}
{{- end }}
