{{- range $key, $value := .Values.worker }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    # Datadog
    tags.datadoghq.com/env: {{ $.Values.environment | quote }}
    tags.datadoghq.com/service: {{ $.Values.project | quote }}
    tags.datadoghq.com/version: {{ $.Values.version | quote }}
  annotations:
    # TODO
    #update the following to support projection
    operator.1password.io/item-path: "vaults/EnvironmentVariables/items/{{ $.Values.project }}-{{ $.Values.environment }}"
    ad.datadoghq.com/{{ $value.name }}.logs: "[{\"source\": \"{{ $value.type }}\"}]"
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $value.name }}
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $value.name }}
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
        # Datadog
        admission.datadoghq.com/enabled: "true"
        # com.datadoghq.ad.logs: '[{"service": {{ $.Values.project | quote }} }]'
        tags.datadoghq.com/env: {{ $.Values.environment | quote }}
        tags.datadoghq.com/service: {{ $.Values.project | quote }}
        tags.datadoghq.com/version: {{ $.Values.version | quote }}
    spec:
      containers:
        - name: {{ $value.name }}
          image: "{{ $value.image }}"
          imagePullPolicy: {{ $value.pullPolicy }}
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
          envFrom: {{- toYaml $value.envFrom | nindent 12 }}
          resources: {{- toYaml $value.resources | nindent 12 }}
          command: {{ $value.command  }}
          args:
          {{- range $value.args }}
            - {{ . }}
          {{- end }}
          volumeMounts:
            {{- range $key, $value := $.Values.keyinjection }}
            - name: {{ $value.name }}
              mountPath: {{ $value.mountPath }}
              readOnly: true
            {{- end }}
            {{- range $key, $value := $value.volumeMounts }}
            - name: {{ $value.name }}
              mountPath: {{ $value.mountPath }}
            {{- end }}
      volumes:
        {{- range $key, $value := $.Values.keyinjection }}
        - name: {{ $value.name }}
          secret:
            secretName: {{ $value.secretName }}
            defaultMode: 384
        {{- end }}
        {{- range $key, $value := $value.volumes }}
        - name: {{ $value.name }}
          persistentVolumeClaim:
            claimName: {{ $value.persistentVolumeClaim.claimName }}
        {{- end }}
{{- end -}}
