{{- range $key, $value := .Values.worker }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    operator.1password.io/item-path: {{ $value.opItemPath }}
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $value.name }}
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $value.name }}
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $value.image }}"
          imagePullPolicy: {{ $value.pullPolicy }}
          envFrom:
            secretRef:
              - name: {{ $value.secretsRef }}
          resources: {{- toYaml $value.resources | nindent 12 }}
          command: {{ $value.command  }}
          args:
          {{- range $value.args }}
            - {{ . }}
          {{- end }}
          volumeMounts:
            {{- range $key, $value := $.Values.keyinjection }}
            - name: {{ $value.name }}
              mountPath: {{ $value.mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        {{- range $key, $value := $.Values.keyinjection }}
        - name: {{ $value.name }}
          secret:
            secretName: {{ $value.secretName }}
        {{- end }}
{{- end -}}
