{{- range $key, $value := .Values.worker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  replicas: {{ $value.replicaCount }}
  selector: 
    matchLabels: {{- include "workerLabels" . | indent 6 }}
  template:
    metadata: 
      labels: {{- include "workerLabels" . | indent 8 }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $value.image }}"
          imagePullPolicy: {{ $value.pullPolicy }}
          resources: {{- toYaml $value.resources | nindent 12 }}
          command: {{ $value.command  }}
          args:
          {{- range $value.args }}
            - {{ . }}
          {{- end }}
          volumeMounts:
            {{- range $key, $value := $.Values.keyinjection }}
            - name: {{ $value.name }}
              mountPath: {{ $value.mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        {{- range $key, $value := $.Values.keyinjection }}
        - name: {{ $value.name }}
          secret:
            secretName: {{ $value.secretName }}
        {{- end }}
{{- end -}}
